// Code generated by ent, DO NOT EDIT.

package jurisdiction

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldEQ(FieldName, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.FieldContainsFold(FieldName, v))
}

// HasLawyers applies the HasEdge predicate on the "lawyers" edge.
func HasLawyers() predicate.Jurisdiction {
	return predicate.Jurisdiction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, LawyersTable, LawyersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLawyersWith applies the HasEdge predicate on the "lawyers" edge with a given conditions (other predicates).
func HasLawyersWith(preds ...predicate.Lawyer) predicate.Jurisdiction {
	return predicate.Jurisdiction(func(s *sql.Selector) {
		step := newLawyersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLawyerJurisdictions applies the HasEdge predicate on the "lawyer_jurisdictions" edge.
func HasLawyerJurisdictions() predicate.Jurisdiction {
	return predicate.Jurisdiction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, LawyerJurisdictionsTable, LawyerJurisdictionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLawyerJurisdictionsWith applies the HasEdge predicate on the "lawyer_jurisdictions" edge with a given conditions (other predicates).
func HasLawyerJurisdictionsWith(preds ...predicate.LawyerJurisdiction) predicate.Jurisdiction {
	return predicate.Jurisdiction(func(s *sql.Selector) {
		step := newLawyerJurisdictionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Jurisdiction) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Jurisdiction) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Jurisdiction) predicate.Jurisdiction {
	return predicate.Jurisdiction(sql.NotPredicates(p))
}
