// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/mvpmaterial"
)

// MvpMaterialCreate is the builder for creating a MvpMaterial entity.
type MvpMaterialCreate struct {
	config
	mutation *MvpMaterialMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (mmc *MvpMaterialCreate) SetName(s string) *MvpMaterialCreate {
	mmc.mutation.SetName(s)
	return mmc
}

// Mutation returns the MvpMaterialMutation object of the builder.
func (mmc *MvpMaterialCreate) Mutation() *MvpMaterialMutation {
	return mmc.mutation
}

// Save creates the MvpMaterial in the database.
func (mmc *MvpMaterialCreate) Save(ctx context.Context) (*MvpMaterial, error) {
	return withHooks(ctx, mmc.sqlSave, mmc.mutation, mmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mmc *MvpMaterialCreate) SaveX(ctx context.Context) *MvpMaterial {
	v, err := mmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mmc *MvpMaterialCreate) Exec(ctx context.Context) error {
	_, err := mmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mmc *MvpMaterialCreate) ExecX(ctx context.Context) {
	if err := mmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mmc *MvpMaterialCreate) check() error {
	if _, ok := mmc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MvpMaterial.name"`)}
	}
	return nil
}

func (mmc *MvpMaterialCreate) sqlSave(ctx context.Context) (*MvpMaterial, error) {
	if err := mmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mmc.mutation.id = &_node.ID
	mmc.mutation.done = true
	return _node, nil
}

func (mmc *MvpMaterialCreate) createSpec() (*MvpMaterial, *sqlgraph.CreateSpec) {
	var (
		_node = &MvpMaterial{config: mmc.config}
		_spec = sqlgraph.NewCreateSpec(mvpmaterial.Table, sqlgraph.NewFieldSpec(mvpmaterial.FieldID, field.TypeInt))
	)
	if value, ok := mmc.mutation.Name(); ok {
		_spec.SetField(mvpmaterial.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// MvpMaterialCreateBulk is the builder for creating many MvpMaterial entities in bulk.
type MvpMaterialCreateBulk struct {
	config
	err      error
	builders []*MvpMaterialCreate
}

// Save creates the MvpMaterial entities in the database.
func (mmcb *MvpMaterialCreateBulk) Save(ctx context.Context) ([]*MvpMaterial, error) {
	if mmcb.err != nil {
		return nil, mmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mmcb.builders))
	nodes := make([]*MvpMaterial, len(mmcb.builders))
	mutators := make([]Mutator, len(mmcb.builders))
	for i := range mmcb.builders {
		func(i int, root context.Context) {
			builder := mmcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MvpMaterialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mmcb *MvpMaterialCreateBulk) SaveX(ctx context.Context) []*MvpMaterial {
	v, err := mmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mmcb *MvpMaterialCreateBulk) Exec(ctx context.Context) error {
	_, err := mmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mmcb *MvpMaterialCreateBulk) ExecX(ctx context.Context) {
	if err := mmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
