// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/mvpmaterial"
)

// MvpMaterial is the model entity for the MvpMaterial schema.
type MvpMaterial struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name                        string `json:"name,omitempty"`
	mvp_planned_route_materials *int
	selectValues                sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MvpMaterial) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mvpmaterial.FieldID:
			values[i] = new(sql.NullInt64)
		case mvpmaterial.FieldName:
			values[i] = new(sql.NullString)
		case mvpmaterial.ForeignKeys[0]: // mvp_planned_route_materials
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MvpMaterial fields.
func (mm *MvpMaterial) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mvpmaterial.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			mm.ID = int(value.Int64)
		case mvpmaterial.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				mm.Name = value.String
			}
		case mvpmaterial.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field mvp_planned_route_materials", value)
			} else if value.Valid {
				mm.mvp_planned_route_materials = new(int)
				*mm.mvp_planned_route_materials = int(value.Int64)
			}
		default:
			mm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MvpMaterial.
// This includes values selected through modifiers, order, etc.
func (mm *MvpMaterial) Value(name string) (ent.Value, error) {
	return mm.selectValues.Get(name)
}

// Update returns a builder for updating this MvpMaterial.
// Note that you need to call MvpMaterial.Unwrap() before calling this method if this MvpMaterial
// was returned from a transaction, and the transaction was committed or rolled back.
func (mm *MvpMaterial) Update() *MvpMaterialUpdateOne {
	return NewMvpMaterialClient(mm.config).UpdateOne(mm)
}

// Unwrap unwraps the MvpMaterial entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mm *MvpMaterial) Unwrap() *MvpMaterial {
	_tx, ok := mm.config.driver.(*txDriver)
	if !ok {
		panic("ent: MvpMaterial is not a transactional entity")
	}
	mm.config.driver = _tx.drv
	return mm
}

// String implements the fmt.Stringer.
func (mm *MvpMaterial) String() string {
	var builder strings.Builder
	builder.WriteString("MvpMaterial(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mm.ID))
	builder.WriteString("name=")
	builder.WriteString(mm.Name)
	builder.WriteByte(')')
	return builder.String()
}

// MvpMaterials is a parsable slice of MvpMaterial.
type MvpMaterials []*MvpMaterial
