// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/mvproute"
)

// MvpRoute is the model entity for the MvpRoute schema.
type MvpRoute struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DayOfWeek holds the value of the "day_of_week" field.
	DayOfWeek    string `json:"day_of_week,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MvpRoute) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mvproute.FieldID:
			values[i] = new(sql.NullInt64)
		case mvproute.FieldName, mvproute.FieldDayOfWeek:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MvpRoute fields.
func (mr *MvpRoute) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mvproute.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			mr.ID = int(value.Int64)
		case mvproute.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				mr.Name = value.String
			}
		case mvproute.FieldDayOfWeek:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field day_of_week", values[i])
			} else if value.Valid {
				mr.DayOfWeek = value.String
			}
		default:
			mr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MvpRoute.
// This includes values selected through modifiers, order, etc.
func (mr *MvpRoute) Value(name string) (ent.Value, error) {
	return mr.selectValues.Get(name)
}

// Update returns a builder for updating this MvpRoute.
// Note that you need to call MvpRoute.Unwrap() before calling this method if this MvpRoute
// was returned from a transaction, and the transaction was committed or rolled back.
func (mr *MvpRoute) Update() *MvpRouteUpdateOne {
	return NewMvpRouteClient(mr.config).UpdateOne(mr)
}

// Unwrap unwraps the MvpRoute entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mr *MvpRoute) Unwrap() *MvpRoute {
	_tx, ok := mr.config.driver.(*txDriver)
	if !ok {
		panic("ent: MvpRoute is not a transactional entity")
	}
	mr.config.driver = _tx.drv
	return mr
}

// String implements the fmt.Stringer.
func (mr *MvpRoute) String() string {
	var builder strings.Builder
	builder.WriteString("MvpRoute(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mr.ID))
	builder.WriteString("name=")
	builder.WriteString(mr.Name)
	builder.WriteString(", ")
	builder.WriteString("day_of_week=")
	builder.WriteString(mr.DayOfWeek)
	builder.WriteByte(')')
	return builder.String()
}

// MvpRoutes is a parsable slice of MvpRoute.
type MvpRoutes []*MvpRoute
