// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/mvpstaff"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// MvpStaffQuery is the builder for querying MvpStaff entities.
type MvpStaffQuery struct {
	config
	ctx        *QueryContext
	order      []mvpstaff.OrderOption
	inters     []Interceptor
	predicates []predicate.MvpStaff
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MvpStaffQuery builder.
func (msq *MvpStaffQuery) Where(ps ...predicate.MvpStaff) *MvpStaffQuery {
	msq.predicates = append(msq.predicates, ps...)
	return msq
}

// Limit the number of records to be returned by this query.
func (msq *MvpStaffQuery) Limit(limit int) *MvpStaffQuery {
	msq.ctx.Limit = &limit
	return msq
}

// Offset to start from.
func (msq *MvpStaffQuery) Offset(offset int) *MvpStaffQuery {
	msq.ctx.Offset = &offset
	return msq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (msq *MvpStaffQuery) Unique(unique bool) *MvpStaffQuery {
	msq.ctx.Unique = &unique
	return msq
}

// Order specifies how the records should be ordered.
func (msq *MvpStaffQuery) Order(o ...mvpstaff.OrderOption) *MvpStaffQuery {
	msq.order = append(msq.order, o...)
	return msq
}

// First returns the first MvpStaff entity from the query.
// Returns a *NotFoundError when no MvpStaff was found.
func (msq *MvpStaffQuery) First(ctx context.Context) (*MvpStaff, error) {
	nodes, err := msq.Limit(1).All(setContextOp(ctx, msq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mvpstaff.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (msq *MvpStaffQuery) FirstX(ctx context.Context) *MvpStaff {
	node, err := msq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MvpStaff ID from the query.
// Returns a *NotFoundError when no MvpStaff ID was found.
func (msq *MvpStaffQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(1).IDs(setContextOp(ctx, msq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mvpstaff.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (msq *MvpStaffQuery) FirstIDX(ctx context.Context) int {
	id, err := msq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MvpStaff entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MvpStaff entity is found.
// Returns a *NotFoundError when no MvpStaff entities are found.
func (msq *MvpStaffQuery) Only(ctx context.Context) (*MvpStaff, error) {
	nodes, err := msq.Limit(2).All(setContextOp(ctx, msq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mvpstaff.Label}
	default:
		return nil, &NotSingularError{mvpstaff.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (msq *MvpStaffQuery) OnlyX(ctx context.Context) *MvpStaff {
	node, err := msq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MvpStaff ID in the query.
// Returns a *NotSingularError when more than one MvpStaff ID is found.
// Returns a *NotFoundError when no entities are found.
func (msq *MvpStaffQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(2).IDs(setContextOp(ctx, msq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mvpstaff.Label}
	default:
		err = &NotSingularError{mvpstaff.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (msq *MvpStaffQuery) OnlyIDX(ctx context.Context) int {
	id, err := msq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MvpStaffs.
func (msq *MvpStaffQuery) All(ctx context.Context) ([]*MvpStaff, error) {
	ctx = setContextOp(ctx, msq.ctx, "All")
	if err := msq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MvpStaff, *MvpStaffQuery]()
	return withInterceptors[[]*MvpStaff](ctx, msq, qr, msq.inters)
}

// AllX is like All, but panics if an error occurs.
func (msq *MvpStaffQuery) AllX(ctx context.Context) []*MvpStaff {
	nodes, err := msq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MvpStaff IDs.
func (msq *MvpStaffQuery) IDs(ctx context.Context) (ids []int, err error) {
	if msq.ctx.Unique == nil && msq.path != nil {
		msq.Unique(true)
	}
	ctx = setContextOp(ctx, msq.ctx, "IDs")
	if err = msq.Select(mvpstaff.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (msq *MvpStaffQuery) IDsX(ctx context.Context) []int {
	ids, err := msq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (msq *MvpStaffQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, msq.ctx, "Count")
	if err := msq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, msq, querierCount[*MvpStaffQuery](), msq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (msq *MvpStaffQuery) CountX(ctx context.Context) int {
	count, err := msq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (msq *MvpStaffQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, msq.ctx, "Exist")
	switch _, err := msq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (msq *MvpStaffQuery) ExistX(ctx context.Context) bool {
	exist, err := msq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MvpStaffQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (msq *MvpStaffQuery) Clone() *MvpStaffQuery {
	if msq == nil {
		return nil
	}
	return &MvpStaffQuery{
		config:     msq.config,
		ctx:        msq.ctx.Clone(),
		order:      append([]mvpstaff.OrderOption{}, msq.order...),
		inters:     append([]Interceptor{}, msq.inters...),
		predicates: append([]predicate.MvpStaff{}, msq.predicates...),
		// clone intermediate query.
		sql:  msq.sql.Clone(),
		path: msq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MvpStaff.Query().
//		GroupBy(mvpstaff.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (msq *MvpStaffQuery) GroupBy(field string, fields ...string) *MvpStaffGroupBy {
	msq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MvpStaffGroupBy{build: msq}
	grbuild.flds = &msq.ctx.Fields
	grbuild.label = mvpstaff.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.MvpStaff.Query().
//		Select(mvpstaff.FieldName).
//		Scan(ctx, &v)
func (msq *MvpStaffQuery) Select(fields ...string) *MvpStaffSelect {
	msq.ctx.Fields = append(msq.ctx.Fields, fields...)
	sbuild := &MvpStaffSelect{MvpStaffQuery: msq}
	sbuild.label = mvpstaff.Label
	sbuild.flds, sbuild.scan = &msq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MvpStaffSelect configured with the given aggregations.
func (msq *MvpStaffQuery) Aggregate(fns ...AggregateFunc) *MvpStaffSelect {
	return msq.Select().Aggregate(fns...)
}

func (msq *MvpStaffQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range msq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, msq); err != nil {
				return err
			}
		}
	}
	for _, f := range msq.ctx.Fields {
		if !mvpstaff.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if msq.path != nil {
		prev, err := msq.path(ctx)
		if err != nil {
			return err
		}
		msq.sql = prev
	}
	return nil
}

func (msq *MvpStaffQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MvpStaff, error) {
	var (
		nodes   = []*MvpStaff{}
		withFKs = msq.withFKs
		_spec   = msq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, mvpstaff.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MvpStaff).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MvpStaff{config: msq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, msq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (msq *MvpStaffQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := msq.querySpec()
	_spec.Node.Columns = msq.ctx.Fields
	if len(msq.ctx.Fields) > 0 {
		_spec.Unique = msq.ctx.Unique != nil && *msq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, msq.driver, _spec)
}

func (msq *MvpStaffQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mvpstaff.Table, mvpstaff.Columns, sqlgraph.NewFieldSpec(mvpstaff.FieldID, field.TypeInt))
	_spec.From = msq.sql
	if unique := msq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if msq.path != nil {
		_spec.Unique = true
	}
	if fields := msq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mvpstaff.FieldID)
		for i := range fields {
			if fields[i] != mvpstaff.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := msq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := msq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := msq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := msq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (msq *MvpStaffQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(msq.driver.Dialect())
	t1 := builder.Table(mvpstaff.Table)
	columns := msq.ctx.Fields
	if len(columns) == 0 {
		columns = mvpstaff.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if msq.sql != nil {
		selector = msq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if msq.ctx.Unique != nil && *msq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range msq.predicates {
		p(selector)
	}
	for _, p := range msq.order {
		p(selector)
	}
	if offset := msq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := msq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MvpStaffGroupBy is the group-by builder for MvpStaff entities.
type MvpStaffGroupBy struct {
	selector
	build *MvpStaffQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (msgb *MvpStaffGroupBy) Aggregate(fns ...AggregateFunc) *MvpStaffGroupBy {
	msgb.fns = append(msgb.fns, fns...)
	return msgb
}

// Scan applies the selector query and scans the result into the given value.
func (msgb *MvpStaffGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, msgb.build.ctx, "GroupBy")
	if err := msgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MvpStaffQuery, *MvpStaffGroupBy](ctx, msgb.build, msgb, msgb.build.inters, v)
}

func (msgb *MvpStaffGroupBy) sqlScan(ctx context.Context, root *MvpStaffQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(msgb.fns))
	for _, fn := range msgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*msgb.flds)+len(msgb.fns))
		for _, f := range *msgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*msgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := msgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MvpStaffSelect is the builder for selecting fields of MvpStaff entities.
type MvpStaffSelect struct {
	*MvpStaffQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mss *MvpStaffSelect) Aggregate(fns ...AggregateFunc) *MvpStaffSelect {
	mss.fns = append(mss.fns, fns...)
	return mss
}

// Scan applies the selector query and scans the result into the given value.
func (mss *MvpStaffSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mss.ctx, "Select")
	if err := mss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MvpStaffQuery, *MvpStaffSelect](ctx, mss.MvpStaffQuery, mss, mss.inters, v)
}

func (mss *MvpStaffSelect) sqlScan(ctx context.Context, root *MvpStaffQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mss.fns))
	for _, fn := range mss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
